spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:test.db
  thymeleaf:
    cache: false

mybatis:
  type-aliases-package: com.model
  mapper-locations: classpath:mapper/*.xml

mapper:
  mappers: com.util.MyMapper
  not-empty: false
